
package com.advancia.Soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserWS", targetNamespace = "http://www.example.org/UserWS/", wsdlLocation = "file:/C:/Users/franc/Desktop/Lavoro/WebappKebab/EsercizioKebab/Soap/UserWS.wsdl")
public class UserWS_Service
    extends Service
{

    private final static URL USERWS_WSDL_LOCATION;
    private final static WebServiceException USERWS_EXCEPTION;
    private final static QName USERWS_QNAME = new QName("http://www.example.org/UserWS/", "UserWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/franc/Desktop/Lavoro/WebappKebab/EsercizioKebab/Soap/UserWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERWS_WSDL_LOCATION = url;
        USERWS_EXCEPTION = e;
    }

    public UserWS_Service() {
        super(__getWsdlLocation(), USERWS_QNAME);
    }

    public UserWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERWS_QNAME, features);
    }

    public UserWS_Service(URL wsdlLocation) {
        super(wsdlLocation, USERWS_QNAME);
    }

    public UserWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERWS_QNAME, features);
    }

    public UserWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserWS
     */
    @WebEndpoint(name = "UserWSSOAP")
    public UserWS getUserWSSOAP() {
        return super.getPort(new QName("http://www.example.org/UserWS/", "UserWSSOAP"), UserWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserWS
     */
    @WebEndpoint(name = "UserWSSOAP")
    public UserWS getUserWSSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/UserWS/", "UserWSSOAP"), UserWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERWS_EXCEPTION!= null) {
            throw USERWS_EXCEPTION;
        }
        return USERWS_WSDL_LOCATION;
    }

}
